const images = {
    iconeAssignment: require('../assets/images/Dashboard/assignment.png'),
    iconeAttendence: require('../assets/images/Dashboard/attendence.png'),
    iconeCalender: require('../assets/images/Dashboard/calendar.png'),
    iconeCircular: require('../assets/images/Dashboard/circular.png'),

    iconeFee: require('../assets/images/Dashboard/fee.png'),
    iconeGallery: require('../assets/images/Dashboard/gallery.png'),
    iconeHomework: require('../assets/images/Dashboard/homework.png'),
    iconeMain: require('../assets/images/Dashboard/main-icon.png'),
    iconeNews: require('../assets/images/Dashboard/news.png'),
    iconePoll: require('../assets/images/Dashboard/poll.png'),
    iconeQuery: require('../assets/images/Dashboard/query.png'),
    iconeVideo: require('../assets/images/Dashboard/video.png'),
    iconeActivity: require('../assets/images/Dashboard/activity.png'),
    iconGurukulamLogo_b: require('../assets/images/Logo/gurukulam_logo_b.png'),
    iconGurukulamLogo_s: require('../assets/images/Logo/gurukulam_logo_s.png'),
    iconDiyaLogo: require('../assets/images/Logo/diya_logo_b.png'),

    iconBg: require('../assets/images/Background/bg.png'),
    iconMenu: require('../assets/images/Menu/menu.png'),
    iconHome: require('../assets/images/Menu/home.png'),
    iconLogout: require('../assets/images/Menu/logout.png'),
    iconManageAc: require('../assets/images/Menu/manageAccount.png'),
    iconNotification: require('../assets/images/Menu/notification.png'),
    iconProfile: require('../assets/images/Menu/user.png'),
    iconBack: require('../assets/images/Back/back.png'),
    iconUserDefault: require('../assets/images/Logo/userDefault.png'),
    iconAlbums: require('../assets/images/albums.png'),
    iconPhotos: require('../assets/images/photos.png'),
    icongalleryPlaceholder: require('../assets/images/gallary_placeholder.jpg'),
    iconCancel: require('../assets/images/cancel.png'),
}
export default images;