export const START_REQUEST_MYPROFILE = 'START_REQUEST_MYPROFILE';
export const END_REQUEST_MYPROFILE = 'END_REQUEST_MYPROFILE';
export const GET_MYPROFILE_DETAILS = 'GET_MYPROFILE_DETAILS';
export const GET_MESSAGE = "GET_MESSAGE";
