export const START_REQUEST_ACTIVITY = 'START_REQUEST_ACTIVITY';
export const END_REQUEST_ACIVITY = 'END_REQUEST_ACIVITY';
export const GET_ACTIVITY = 'GET_ACTIVITY';
export const GET_MESSAGE = "GET_MESSAGE";
