export const START_REQUEST = 'START_REQUEST';
export const END_REQUEST = 'END_REQUEST';
export const GET_SCHOOL_CODE = 'GET_SCHOOL_CODE';
export const GET_CAMPUS_LIST = 'GET_CAMPUS_LIST';
export const GET_BATCHLIST_BY_CAMPUSID = 'GET_BATCHLIST_BY_CAMPUSID';
export const GET_LOGIN = 'GET_LOGIN';