export const START_REQUEST_CAENTEEN = 'START_REQUEST_CAENTEEN';
export const END_REQUEST_CANTEEN = 'END_REQUEST_CANTEEN';
export const GET_CAMPUS_CANTEEN_LIST = 'GET_CAMPUS_CANTEEN_LIST';
export const GET_CANTEEN_MENU_ITEM_LIST = 'GET_CANTEEN_MENU_ITEM_LIST';
export const GET_MESSAGE = "GET_MESSAGE";
