export const START_REQUEST_GALLERY = 'START_REQUEST_GALLERY';
export const END_REQUEST_GALLERY = 'END_REQUEST_GALLERY';
export const GET_GALLERY_DETAILS = 'GET_GALLERY_DETAILS';
export const GET_MESSAGE = "GET_MESSAGE";
