export const START_REQUEST_POLL = 'START_REQUEST_POLL';
export const END_REQUEST_POLL = 'END_REQUEST_POLL';
export const GET_POLL_DETAILS = 'GET_POLL_DETAILS';
export const GET_MESSAGE = "GET_MESSAGE";
